name: icd
namespace: bf-icd
defaultLanguage: en
nluThreshold: 0.75
timezoneOffset: 0
allowContextualQuestions: false
instance:
  name: Default Instance
  host: 'http://rasa:5005'
  projectId: eEb2rA32449JjTEMS
