name: ecom
namespace: bf-ecom
defaultLanguage: en
nluThreshold: 0.75
timezoneOffset: 0
allowContextualQuestions: false
instance:
  name: Default Instance
  host: 'http://localhost:5005'
  projectId: usaCi6ittMNELwhzk
